# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54530cd347fb07de9ea04ff8f3cfbf5b97c64ba5646219c704cb0ba0b920845cdb22628228040736f01c399dd7b5f1bf2f73d363ccde1ece8c86eeabee911fce

test:
  secret_key_base: 704bd8c1ac476e08e4ef5988bc34bffab598e81b992805831d9d6f9e2a959a1176e42f9d900f93ee1f6a121e6d4f6a57d3f326ed445a8b889f53034a5cba464b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
